version: '2'
services:
    bitcoind:
      image: bitcoind
      networks: [lnd]
      build:
          context: bitcoind
          dockerfile: Dockerfile
      volumes:
          - shared:/rpc
          - bitcoin:/data
          - ./bitcoind/bitcoin.conf:/bitcoin.conf
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - DEBUG
        - MINING_ADDRESS
      entrypoint: ["./start-bitcoind.sh", "-conf=/bitcoin.conf"]

    lnd:
      image: lnd
      networks: [lnd]
      build:
        context: lnd 
        dockerfile: Dockerfile
      security_opt:
        - seccomp=lnd/lnd-seccomp.json
      environment:
        - RPCUSER
        - BACKEND
        - RPCPASS
        - NETWORK
        - CHAIN
        - DEBUG
      ports:
          - 8080:8080
      volumes:
          - shared:/rpc
          - bitcoin:/data
          - ./lnd/lnd.conf:/lnd.conf
      entrypoint: ["lnd", "--configfile=/lnd.conf"]

networks:
  lnd:

volumes:
  shared:
    driver: local

  bitcoin:
    driver: local

  lndconf:
    driver: local
