version: '2'
services:
    btcd:
      image: btcd
      networks: [lnd]
      build:
          context: btcd
          dockerfile: Dockerfile
      volumes:
          - shared:/rpc
          - ./btcd/btcd.conf:/btcd.conf
      environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - DEBUG
      command: ["btcd", "--configfile=/btcd.conf"]
    bitcoind:
      image: bitcoind
      networks: [lnd]
      build:
          context: bitcoind
          dockerfile: Dockerfile
      volumes:
          - ./bitcoind/bitcoin.conf:/bitcoin.conf
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK
        - DEBUG
      command: ["bitcoind", "-conf=/bitcoin.conf"]
    lndalice:
      image: lnd
      networks: [lnd]
      build:
        context: lnd 
        dockerfile: Dockerfile
        #security_opt:
        #  - seccomp=lnd/lnd-seccomp.json
      environment:
        - RPCUSER
        - RPCPASS
        - BACKEND
        - NETWORK
        - CHAIN
        - DEBUG
      volumes:
          - shared:/rpc
          - ./lnd/btcd-lnd.conf:/btcd-lnd.conf
          - ./lnd/bitcoind-lnd.conf:/bitcoind-lnd.conf
      command: ["lnd", "--configfile=/$BACKEND-lnd.conf"]
      ports:
          - 8080:8080
    lndbob:
      image: lnd
      networks: [lnd]
      build:
        context: lnd
        dockerfile: Dockerfile
        #security_opt:
        #  - seccomp=lnd/lnd-seccomp.json
      environment:
        - RPCUSER
        - RPCPASS
        - BACKEND
        - NETWORK
        - CHAIN
        - DEBUG
      volumes:
          - shared:/rpc
          - ./lnd/btcd-lnd.conf:/btcd-lnd.conf
          - ./lnd/bitcoind-lnd.conf:/bitcoind-lnd.conf
      command: ["lnd", "--configfile=/$BACKEND-lnd.conf"]
    rtl:
      image: rtl
      networks: [lnd]
      build:
        context: rtl
        dockerfile: Dockerfile
        #security_opt:
        #  - seccomp=lnd/lnd-seccomp.json
      environment:
        - RPCUSER
        - RPCPASS
        - BACKEND
        - NETWORK
        - CHAIN
        - DEBUG
      volumes:
          - ./simnet:/lnd/data/chain/bitcoin/simnet/
          - ./lnd/btcd-lnd.conf:/btcd-lnd.conf
          - ./lnd/bitcoind-lnd.conf:/bitcoind-lnd.conf
      command: ["node", "rtl", "--lndir", "/lnd/data/chain/bitcoin/simnet"]
      ports:
         - 80:3000


networks:
  lnd:

volumes:
  shared:
    driver: local

  lnd:
    driver: local
